import type { Shipment } from "./types";

// Test shipping records. Order IDs line up with lib/sources/mock-orders.ts so
// the Logistik view and the Jualan view tell the same story.
export const mockShipments: Shipment[] = [
  {
    trackingNo: "630881204517",
    orderId: "#CA-1048",
    courier: "J&T Express",
    provider: "easyparcel",
    service: "Standard Domestik",
    recipient: "Farah Nadia",
    initials: "FN",
    destination: "Shah Alam, Selangor",
    postcode: "40150",
    weightKg: 0.6,
    cost: 5.9,
    status: "Sedang dihantar",
    bookedAt: "20 Jul 2026, 11:20 AM",
    estimatedDelivery: "22 Jul 2026",
    checkpoints: [
      { time: "20 Jul, 11:20 AM", status: "Pesanan dibuat", location: "KretivCo Fulfilment, Bangi" },
      { time: "20 Jul, 4:45 PM", status: "Bungkusan diambil kurier", location: "J&T Bangi DC" },
      { time: "21 Jul, 8:02 AM", status: "Tiba di hab penyusunan", location: "J&T Shah Alam Hub" },
      { time: "22 Jul, 9:15 AM", status: "Dalam perjalanan ke penerima", location: "Shah Alam, Selangor" },
    ],
  },
  {
    trackingNo: "630881204498",
    orderId: "#CA-1047",
    courier: "J&T Express",
    provider: "easyparcel",
    service: "Standard Domestik",
    recipient: "Syafiq Roslan",
    initials: "SR",
    destination: "Kuantan, Pahang",
    postcode: "25200",
    weightKg: 0.3,
    cost: 7.4,
    status: "Dalam transit",
    bookedAt: "20 Jul 2026, 10:05 AM",
    estimatedDelivery: "23 Jul 2026",
    checkpoints: [
      { time: "20 Jul, 10:05 AM", status: "Pesanan dibuat", location: "KretivCo Fulfilment, Bangi" },
      { time: "20 Jul, 4:45 PM", status: "Bungkusan diambil kurier", location: "J&T Bangi DC" },
      { time: "21 Jul, 6:30 PM", status: "Tiba di hab penyusunan", location: "J&T Temerloh Hub" },
    ],
  },
  {
    trackingNo: "EP418823901MY",
    orderId: "#CA-1046",
    courier: "Pos Laju",
    provider: "easyparcel",
    service: "Pos Laju Next Day",
    recipient: "Aina Sofea",
    initials: "AS",
    destination: "Georgetown, Pulau Pinang",
    postcode: "10450",
    weightKg: 0.9,
    cost: 9.2,
    status: "Dihantar",
    bookedAt: "19 Jul 2026, 2:10 PM",
    estimatedDelivery: "21 Jul 2026",
    checkpoints: [
      { time: "19 Jul, 2:10 PM", status: "Pesanan dibuat", location: "KretivCo Fulfilment, Bangi" },
      { time: "19 Jul, 5:30 PM", status: "Bungkusan diambil kurier", location: "Pos Laju Kajang" },
      { time: "20 Jul, 7:44 AM", status: "Tiba di hab penyusunan", location: "Pos Laju Butterworth" },
      { time: "20 Jul, 2:18 PM", status: "Dalam perjalanan ke penerima", location: "Georgetown, Pulau Pinang" },
      { time: "20 Jul, 4:51 PM", status: "Berjaya dihantar — diterima oleh penerima", location: "Georgetown, Pulau Pinang" },
    ],
  },
  {
    trackingNo: "NVMY418290073",
    orderId: "#CA-1045",
    courier: "Ninja Van",
    provider: "easyparcel",
    service: "Standard Domestik",
    recipient: "Mohd Firdaus",
    initials: "MF",
    destination: "Johor Bahru, Johor",
    postcode: "81100",
    weightKg: 1.2,
    cost: 8.5,
    status: "Dihantar",
    bookedAt: "19 Jul 2026, 9:40 AM",
    estimatedDelivery: "22 Jul 2026",
    checkpoints: [
      { time: "19 Jul, 9:40 AM", status: "Pesanan dibuat", location: "KretivCo Fulfilment, Bangi" },
      { time: "19 Jul, 3:15 PM", status: "Bungkusan diambil kurier", location: "Ninja Van Seri Kembangan" },
      { time: "20 Jul, 11:02 AM", status: "Tiba di hab penyusunan", location: "Ninja Van Skudai Hub" },
      { time: "21 Jul, 10:26 AM", status: "Berjaya dihantar — diterima oleh penerima", location: "Johor Bahru, Johor" },
    ],
  },
  {
    trackingNo: "630881204312",
    orderId: "#CA-1044",
    courier: "J&T Express",
    provider: "easyparcel",
    service: "Standard Domestik",
    recipient: "Nurin Izzati",
    initials: "NI",
    destination: "Kota Bharu, Kelantan",
    postcode: "15200",
    weightKg: 0.3,
    cost: 8.9,
    status: "Gagal dihantar",
    bookedAt: "17 Jul 2026, 1:24 PM",
    estimatedDelivery: "20 Jul 2026",
    checkpoints: [
      { time: "17 Jul, 1:24 PM", status: "Pesanan dibuat", location: "KretivCo Fulfilment, Bangi" },
      { time: "17 Jul, 5:02 PM", status: "Bungkusan diambil kurier", location: "J&T Bangi DC" },
      { time: "19 Jul, 8:40 AM", status: "Tiba di hab penyusunan", location: "J&T Kota Bharu Hub" },
      { time: "19 Jul, 3:12 PM", status: "Cubaan penghantaran gagal — penerima tiada", location: "Kota Bharu, Kelantan", failed: true },
      { time: "20 Jul, 4:30 PM", status: "Dipulangkan ke penghantar", location: "J&T Kota Bharu Hub", failed: true },
    ],
  },
  {
    trackingNo: "630881204287",
    orderId: "#CA-1042",
    courier: "J&T Express",
    provider: "easyparcel",
    service: "Standard Domestik",
    recipient: "Amirul Hakim",
    initials: "AH",
    destination: "Seremban, Negeri Sembilan",
    postcode: "70300",
    weightKg: 0.6,
    cost: 5.9,
    status: "Dihantar",
    bookedAt: "16 Jul 2026, 10:32 AM",
    estimatedDelivery: "18 Jul 2026",
    checkpoints: [
      { time: "16 Jul, 10:32 AM", status: "Pesanan dibuat", location: "KretivCo Fulfilment, Bangi" },
      { time: "16 Jul, 4:45 PM", status: "Bungkusan diambil kurier", location: "J&T Bangi DC" },
      { time: "17 Jul, 8:20 AM", status: "Tiba di hab penyusunan", location: "J&T Seremban Hub" },
      { time: "17 Jul, 2:05 PM", status: "Berjaya dihantar — diterima oleh penerima", location: "Seremban, Negeri Sembilan" },
    ],
  },
  {
    trackingNo: "MYJ771203845",
    orderId: "#CA-1043",
    courier: "DHL eCommerce",
    provider: "easyparcel",
    service: "DHL Domestik",
    recipient: "Daniel Lim",
    initials: "DL",
    destination: "Petaling Jaya, Selangor",
    postcode: "47810",
    weightKg: 0.6,
    cost: 6.3,
    status: "Dihantar",
    bookedAt: "17 Jul 2026, 11:15 AM",
    estimatedDelivery: "19 Jul 2026",
    checkpoints: [
      { time: "17 Jul, 11:15 AM", status: "Pesanan dibuat", location: "KretivCo Fulfilment, Bangi" },
      { time: "17 Jul, 4:20 PM", status: "Bungkusan diambil kurier", location: "DHL Puchong" },
      { time: "18 Jul, 9:05 AM", status: "Dalam perjalanan ke penerima", location: "Petaling Jaya, Selangor" },
      { time: "18 Jul, 1:47 PM", status: "Berjaya dihantar — diterima oleh penerima", location: "Petaling Jaya, Selangor" },
    ],
  },
  {
    trackingNo: "630881204620",
    orderId: "#CA-1049",
    courier: "J&T Express",
    provider: "easyparcel",
    service: "Standard Domestik",
    recipient: "Hafiz Kamarudin",
    initials: "HK",
    destination: "Ipoh, Perak",
    postcode: "31400",
    weightKg: 0.6,
    cost: 6.8,
    status: "Menunggu pickup",
    bookedAt: "22 Jul 2026, 9:12 AM",
    estimatedDelivery: "24 Jul 2026",
    checkpoints: [
      { time: "22 Jul, 9:12 AM", status: "Pesanan dibuat", location: "KretivCo Fulfilment, Bangi" },
    ],
  },
  {
    trackingNo: "NVMY418290511",
    orderId: "#CA-1050",
    courier: "Ninja Van",
    provider: "easyparcel",
    service: "Standard Domestik",
    recipient: "Siti Aisyah",
    initials: "SA",
    destination: "Kuching, Sarawak",
    postcode: "93350",
    weightKg: 0.9,
    cost: 14.5,
    status: "Menunggu pickup",
    bookedAt: "22 Jul 2026, 9:48 AM",
    estimatedDelivery: "26 Jul 2026",
    checkpoints: [
      { time: "22 Jul, 9:48 AM", status: "Pesanan dibuat", location: "KretivCo Fulfilment, Bangi" },
    ],
  },
];
